name: Gate Alpha Release
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    env:
      GOPATH: /home/runner/go
      GOCACHE: /home/runner/.cache/go
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Hi
        run: |
          echo hi from fargate